---
- hosts: all
  become: true
  tasks:
    - name: Install Apache HTTP Servers
      yum:
        name: httpd
        state: latest
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: Start the Apache HTTP Servers
      service:
        name: httpd
        state: started
        enabled: true
...

