---
- hosts: all
  become: true
  vars:
    companyName: Expertit
    loaction: Pune
  tasks:
    - name: Install Apache HTTP Servers
      yum:
        name: httpd
        state: latest
    - name: Start the Apache HTTP Servers
      service:
        name: httpd
        state: started
        enabled: true
    - name: Copy index.html
      template:
        src: index.html
        dest: /var/www/html/index.html
...

