---
- hosts: all
  become: true
  vars_files:
   - 08variable.yml
  tasks:
    - name: Install Apache HTTP Servers
      yum:
        name: httpd
        state: latest
        
    - name: Copy index.html
      template:
        src: index.html
        dest: /var/www/html/index.html
      notify:
       - Re-Start the Apache Http Servers            
       
   handlers:     
    - name: Re-Start the Apache HTTP Servers
      service:
        name: httpd
        state: restarted
        enabled: true
...


