---
- hosts: all
  become: true
  vars:
    env: dev
  vars_files:
    - "{{ env }}_vars.yml"
  tasks:
    - name: Install Apache HTTP Server
      yum:
        name: httpd
        state: latest

    - name: Copy index.html
      template:
        src: index.html
        dest: /var/www/html/index.html
      notify:
        - Restart Apache HTTP Server

  handlers:
    - name: Restart Apache HTTP Server
      service:
        name: httpd
        state: restarted
        enabled: true
...

